//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FSBaseStation.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("120")]
        public double VelXMax {
            get {
                return ((double)(this["VelXMax"]));
            }
            set {
                this["VelXMax"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double VelXMin {
            get {
                return ((double)(this["VelXMin"]));
            }
            set {
                this["VelXMin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public double VelYMax {
            get {
                return ((double)(this["VelYMax"]));
            }
            set {
                this["VelYMax"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-50")]
        public double VelYMin {
            get {
                return ((double)(this["VelYMin"]));
            }
            set {
                this["VelYMin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int ECULeftTorqueDemandXLag {
            get {
                return ((int)(this["ECULeftTorqueDemandXLag"]));
            }
            set {
                this["ECULeftTorqueDemandXLag"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public double ECULeftTorqueDemandXLagSpacing {
            get {
                return ((double)(this["ECULeftTorqueDemandXLagSpacing"]));
            }
            set {
                this["ECULeftTorqueDemandXLagSpacing"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("22")]
        public double ECULeftTorqueDemandXLagMax {
            get {
                return ((double)(this["ECULeftTorqueDemandXLagMax"]));
            }
            set {
                this["ECULeftTorqueDemandXLagMax"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("150")]
        public double ECULeftTorqueDemandXNofDataPoint {
            get {
                return ((double)(this["ECULeftTorqueDemandXNofDataPoint"]));
            }
            set {
                this["ECULeftTorqueDemandXNofDataPoint"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int ECURightTorqueDemandXLag {
            get {
                return ((int)(this["ECURightTorqueDemandXLag"]));
            }
            set {
                this["ECURightTorqueDemandXLag"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public double ECURightTorqueDemandXLagSpacing {
            get {
                return ((double)(this["ECURightTorqueDemandXLagSpacing"]));
            }
            set {
                this["ECURightTorqueDemandXLagSpacing"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("22")]
        public double ECURightTorqueDemandXLagMax {
            get {
                return ((double)(this["ECURightTorqueDemandXLagMax"]));
            }
            set {
                this["ECURightTorqueDemandXLagMax"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("150")]
        public double ECURightTorqueDemandXNofDataPoint {
            get {
                return ((double)(this["ECURightTorqueDemandXNofDataPoint"]));
            }
            set {
                this["ECURightTorqueDemandXNofDataPoint"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public double ECULeftTorqueDemandMax {
            get {
                return ((double)(this["ECULeftTorqueDemandMax"]));
            }
            set {
                this["ECULeftTorqueDemandMax"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double ECULeftTorqueDemandMin {
            get {
                return ((double)(this["ECULeftTorqueDemandMin"]));
            }
            set {
                this["ECULeftTorqueDemandMin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public double ECURightTorqueDemandMax {
            get {
                return ((double)(this["ECURightTorqueDemandMax"]));
            }
            set {
                this["ECURightTorqueDemandMax"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double ECURightTorqueDemandMin {
            get {
                return ((double)(this["ECURightTorqueDemandMin"]));
            }
            set {
                this["ECURightTorqueDemandMin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("150")]
        public double ECUAcclerationDemandXNofDataPoint {
            get {
                return ((double)(this["ECUAcclerationDemandXNofDataPoint"]));
            }
            set {
                this["ECUAcclerationDemandXNofDataPoint"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int ECUAcclerationDemandXLag {
            get {
                return ((int)(this["ECUAcclerationDemandXLag"]));
            }
            set {
                this["ECUAcclerationDemandXLag"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public double ECUAcclerationDemandXLagSpacing {
            get {
                return ((double)(this["ECUAcclerationDemandXLagSpacing"]));
            }
            set {
                this["ECUAcclerationDemandXLagSpacing"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("22")]
        public double ECUAcclerationDemandXLagMax {
            get {
                return ((double)(this["ECUAcclerationDemandXLagMax"]));
            }
            set {
                this["ECUAcclerationDemandXLagMax"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public double ECUAcclerationDemandMax {
            get {
                return ((double)(this["ECUAcclerationDemandMax"]));
            }
            set {
                this["ECUAcclerationDemandMax"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double ECUAcclerationDemandMin {
            get {
                return ((double)(this["ECUAcclerationDemandMin"]));
            }
            set {
                this["ECUAcclerationDemandMin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("150")]
        public double ECUFrontBrakeDemandXNofDataPoint {
            get {
                return ((double)(this["ECUFrontBrakeDemandXNofDataPoint"]));
            }
            set {
                this["ECUFrontBrakeDemandXNofDataPoint"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int ECUFrontBrakeDemandXLag {
            get {
                return ((int)(this["ECUFrontBrakeDemandXLag"]));
            }
            set {
                this["ECUFrontBrakeDemandXLag"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public double ECUFrontBrakeDemandXLagSpacing {
            get {
                return ((double)(this["ECUFrontBrakeDemandXLagSpacing"]));
            }
            set {
                this["ECUFrontBrakeDemandXLagSpacing"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public double ECUFrontBrakeDemandMax {
            get {
                return ((double)(this["ECUFrontBrakeDemandMax"]));
            }
            set {
                this["ECUFrontBrakeDemandMax"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double ECUFrontBrakeDemandMin {
            get {
                return ((double)(this["ECUFrontBrakeDemandMin"]));
            }
            set {
                this["ECUFrontBrakeDemandMin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("22")]
        public double ECUFrontBrakeDemandXLagMax {
            get {
                return ((double)(this["ECUFrontBrakeDemandXLagMax"]));
            }
            set {
                this["ECUFrontBrakeDemandXLagMax"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("150")]
        public double KistlerVelXXNofDataPoint {
            get {
                return ((double)(this["KistlerVelXXNofDataPoint"]));
            }
            set {
                this["KistlerVelXXNofDataPoint"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int KistlerVelXXLag {
            get {
                return ((int)(this["KistlerVelXXLag"]));
            }
            set {
                this["KistlerVelXXLag"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public double KistlerVelXXLagSpacing {
            get {
                return ((double)(this["KistlerVelXXLagSpacing"]));
            }
            set {
                this["KistlerVelXXLagSpacing"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public double KistlerVelXMax {
            get {
                return ((double)(this["KistlerVelXMax"]));
            }
            set {
                this["KistlerVelXMax"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double KistlerVelXMin {
            get {
                return ((double)(this["KistlerVelXMin"]));
            }
            set {
                this["KistlerVelXMin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("22")]
        public double KistlerVelXXLagMax {
            get {
                return ((double)(this["KistlerVelXXLagMax"]));
            }
            set {
                this["KistlerVelXXLagMax"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public double KistlerVelYXLagSpacing {
            get {
                return ((double)(this["KistlerVelYXLagSpacing"]));
            }
            set {
                this["KistlerVelYXLagSpacing"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public double KistlerVelYXLagMax {
            get {
                return ((double)(this["KistlerVelYXLagMax"]));
            }
            set {
                this["KistlerVelYXLagMax"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public double KistlerVelYXNofDataPoint {
            get {
                return ((double)(this["KistlerVelYXNofDataPoint"]));
            }
            set {
                this["KistlerVelYXNofDataPoint"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int KistlerVelYXLag {
            get {
                return ((int)(this["KistlerVelYXLag"]));
            }
            set {
                this["KistlerVelYXLag"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public double KistlerVelYMax {
            get {
                return ((double)(this["KistlerVelYMax"]));
            }
            set {
                this["KistlerVelYMax"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double KistlerVelYMin {
            get {
                return ((double)(this["KistlerVelYMin"]));
            }
            set {
                this["KistlerVelYMin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public double KistlerAcclerationXXLagSpacing {
            get {
                return ((double)(this["KistlerAcclerationXXLagSpacing"]));
            }
            set {
                this["KistlerAcclerationXXLagSpacing"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public double KistlerAcclerationXXLagMax {
            get {
                return ((double)(this["KistlerAcclerationXXLagMax"]));
            }
            set {
                this["KistlerAcclerationXXLagMax"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public double KistlerAcclerationXXNofDataPoint {
            get {
                return ((double)(this["KistlerAcclerationXXNofDataPoint"]));
            }
            set {
                this["KistlerAcclerationXXNofDataPoint"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int KistlerAcclerationXXLag {
            get {
                return ((int)(this["KistlerAcclerationXXLag"]));
            }
            set {
                this["KistlerAcclerationXXLag"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public double KistlerAcclerationXMax {
            get {
                return ((double)(this["KistlerAcclerationXMax"]));
            }
            set {
                this["KistlerAcclerationXMax"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double KistlerAcclerationXMin {
            get {
                return ((double)(this["KistlerAcclerationXMin"]));
            }
            set {
                this["KistlerAcclerationXMin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public double KistlerAcclerationYXLagSpacing {
            get {
                return ((double)(this["KistlerAcclerationYXLagSpacing"]));
            }
            set {
                this["KistlerAcclerationYXLagSpacing"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public double KistlerAcclerationYXLagMax {
            get {
                return ((double)(this["KistlerAcclerationYXLagMax"]));
            }
            set {
                this["KistlerAcclerationYXLagMax"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public double KistlerAcclerationYXNofDataPoint {
            get {
                return ((double)(this["KistlerAcclerationYXNofDataPoint"]));
            }
            set {
                this["KistlerAcclerationYXNofDataPoint"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int KistlerAcclerationYXLag {
            get {
                return ((int)(this["KistlerAcclerationYXLag"]));
            }
            set {
                this["KistlerAcclerationYXLag"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public double KistlerAcclerationYMax {
            get {
                return ((double)(this["KistlerAcclerationYMax"]));
            }
            set {
                this["KistlerAcclerationYMax"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double KistlerAcclerationYMin {
            get {
                return ((double)(this["KistlerAcclerationYMin"]));
            }
            set {
                this["KistlerAcclerationYMin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public double RightInverterSpeedXLagSpacing {
            get {
                return ((double)(this["RightInverterSpeedXLagSpacing"]));
            }
            set {
                this["RightInverterSpeedXLagSpacing"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public double RightInverterSpeedXLagMax {
            get {
                return ((double)(this["RightInverterSpeedXLagMax"]));
            }
            set {
                this["RightInverterSpeedXLagMax"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public double RightInverterSpeedXNofDataPoint {
            get {
                return ((double)(this["RightInverterSpeedXNofDataPoint"]));
            }
            set {
                this["RightInverterSpeedXNofDataPoint"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int RightInverterSpeedXLag {
            get {
                return ((int)(this["RightInverterSpeedXLag"]));
            }
            set {
                this["RightInverterSpeedXLag"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public double RightInverterSpeedMax {
            get {
                return ((double)(this["RightInverterSpeedMax"]));
            }
            set {
                this["RightInverterSpeedMax"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double RightInverterSpeedMin {
            get {
                return ((double)(this["RightInverterSpeedMin"]));
            }
            set {
                this["RightInverterSpeedMin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public double RightInverterMechanicalPowerXLagSpacing {
            get {
                return ((double)(this["RightInverterMechanicalPowerXLagSpacing"]));
            }
            set {
                this["RightInverterMechanicalPowerXLagSpacing"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public double RightInverterMechanicalPowerXLagMax {
            get {
                return ((double)(this["RightInverterMechanicalPowerXLagMax"]));
            }
            set {
                this["RightInverterMechanicalPowerXLagMax"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public double RightInverterMechanicalPowerXNofDataPoint {
            get {
                return ((double)(this["RightInverterMechanicalPowerXNofDataPoint"]));
            }
            set {
                this["RightInverterMechanicalPowerXNofDataPoint"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int RightInverterMechanicalPowerXLag {
            get {
                return ((int)(this["RightInverterMechanicalPowerXLag"]));
            }
            set {
                this["RightInverterMechanicalPowerXLag"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public double RightInverterMechanicalPowerMax {
            get {
                return ((double)(this["RightInverterMechanicalPowerMax"]));
            }
            set {
                this["RightInverterMechanicalPowerMax"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double RightInverterMechanicalPowerMin {
            get {
                return ((double)(this["RightInverterMechanicalPowerMin"]));
            }
            set {
                this["RightInverterMechanicalPowerMin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public double RightInverterAbsolutePhaseCurrentXLagSpacing {
            get {
                return ((double)(this["RightInverterAbsolutePhaseCurrentXLagSpacing"]));
            }
            set {
                this["RightInverterAbsolutePhaseCurrentXLagSpacing"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public double RightInverterAbsolutePhaseCurrentXLagMax {
            get {
                return ((double)(this["RightInverterAbsolutePhaseCurrentXLagMax"]));
            }
            set {
                this["RightInverterAbsolutePhaseCurrentXLagMax"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public double RightInverterAbsolutePhaseCurrentXNofDataPoint {
            get {
                return ((double)(this["RightInverterAbsolutePhaseCurrentXNofDataPoint"]));
            }
            set {
                this["RightInverterAbsolutePhaseCurrentXNofDataPoint"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int RightInverterAbsolutePhaseCurrentXLag {
            get {
                return ((int)(this["RightInverterAbsolutePhaseCurrentXLag"]));
            }
            set {
                this["RightInverterAbsolutePhaseCurrentXLag"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public double RightInverterAbsolutePhaseCurrentMax {
            get {
                return ((double)(this["RightInverterAbsolutePhaseCurrentMax"]));
            }
            set {
                this["RightInverterAbsolutePhaseCurrentMax"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double RightInverterAbsolutePhaseCurrentMin {
            get {
                return ((double)(this["RightInverterAbsolutePhaseCurrentMin"]));
            }
            set {
                this["RightInverterAbsolutePhaseCurrentMin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public double RightInverterLinkVoltageDCXLagSpacing {
            get {
                return ((double)(this["RightInverterLinkVoltageDCXLagSpacing"]));
            }
            set {
                this["RightInverterLinkVoltageDCXLagSpacing"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public double RightInverterLinkVoltageDCXLagMax {
            get {
                return ((double)(this["RightInverterLinkVoltageDCXLagMax"]));
            }
            set {
                this["RightInverterLinkVoltageDCXLagMax"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public double RightInverterLinkVoltageDCXNofDataPoint {
            get {
                return ((double)(this["RightInverterLinkVoltageDCXNofDataPoint"]));
            }
            set {
                this["RightInverterLinkVoltageDCXNofDataPoint"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int RightInverterLinkVoltageDCXLag {
            get {
                return ((int)(this["RightInverterLinkVoltageDCXLag"]));
            }
            set {
                this["RightInverterLinkVoltageDCXLag"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public double RightInverterLinkVoltageDCMax {
            get {
                return ((double)(this["RightInverterLinkVoltageDCMax"]));
            }
            set {
                this["RightInverterLinkVoltageDCMax"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double RightInverterLinkVoltageDCMin {
            get {
                return ((double)(this["RightInverterLinkVoltageDCMin"]));
            }
            set {
                this["RightInverterLinkVoltageDCMin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public double LeftInverterSpeedXLagSpacing {
            get {
                return ((double)(this["LeftInverterSpeedXLagSpacing"]));
            }
            set {
                this["LeftInverterSpeedXLagSpacing"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public double LeftInverterSpeedXLagMax {
            get {
                return ((double)(this["LeftInverterSpeedXLagMax"]));
            }
            set {
                this["LeftInverterSpeedXLagMax"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public double LeftInverterSpeedXNofDataPoint {
            get {
                return ((double)(this["LeftInverterSpeedXNofDataPoint"]));
            }
            set {
                this["LeftInverterSpeedXNofDataPoint"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int LeftInverterSpeedXLag {
            get {
                return ((int)(this["LeftInverterSpeedXLag"]));
            }
            set {
                this["LeftInverterSpeedXLag"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public double LeftInverterSpeedMax {
            get {
                return ((double)(this["LeftInverterSpeedMax"]));
            }
            set {
                this["LeftInverterSpeedMax"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double LeftInverterSpeedMin {
            get {
                return ((double)(this["LeftInverterSpeedMin"]));
            }
            set {
                this["LeftInverterSpeedMin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public double LeftInverterMechanicalPowerXLagSpacing {
            get {
                return ((double)(this["LeftInverterMechanicalPowerXLagSpacing"]));
            }
            set {
                this["LeftInverterMechanicalPowerXLagSpacing"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public double LeftInverterMechanicalPowerXLagMax {
            get {
                return ((double)(this["LeftInverterMechanicalPowerXLagMax"]));
            }
            set {
                this["LeftInverterMechanicalPowerXLagMax"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public double LeftInverterMechanicalPowerXNofDataPoint {
            get {
                return ((double)(this["LeftInverterMechanicalPowerXNofDataPoint"]));
            }
            set {
                this["LeftInverterMechanicalPowerXNofDataPoint"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int LeftInverterMechanicalPowerXLag {
            get {
                return ((int)(this["LeftInverterMechanicalPowerXLag"]));
            }
            set {
                this["LeftInverterMechanicalPowerXLag"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public double LeftInverterMechanicalPowerMax {
            get {
                return ((double)(this["LeftInverterMechanicalPowerMax"]));
            }
            set {
                this["LeftInverterMechanicalPowerMax"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double LeftInverterMechanicalPowerMin {
            get {
                return ((double)(this["LeftInverterMechanicalPowerMin"]));
            }
            set {
                this["LeftInverterMechanicalPowerMin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public double LeftInverterAbsolutePhaseCurrentXLagSpacing {
            get {
                return ((double)(this["LeftInverterAbsolutePhaseCurrentXLagSpacing"]));
            }
            set {
                this["LeftInverterAbsolutePhaseCurrentXLagSpacing"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public double LeftInverterAbsolutePhaseCurrentXLagMax {
            get {
                return ((double)(this["LeftInverterAbsolutePhaseCurrentXLagMax"]));
            }
            set {
                this["LeftInverterAbsolutePhaseCurrentXLagMax"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public double LeftInverterAbsolutePhaseCurrentXNofDataPoint {
            get {
                return ((double)(this["LeftInverterAbsolutePhaseCurrentXNofDataPoint"]));
            }
            set {
                this["LeftInverterAbsolutePhaseCurrentXNofDataPoint"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int LeftInverterAbsolutePhaseCurrentXLag {
            get {
                return ((int)(this["LeftInverterAbsolutePhaseCurrentXLag"]));
            }
            set {
                this["LeftInverterAbsolutePhaseCurrentXLag"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public double LeftInverterAbsolutePhaseCurrentMax {
            get {
                return ((double)(this["LeftInverterAbsolutePhaseCurrentMax"]));
            }
            set {
                this["LeftInverterAbsolutePhaseCurrentMax"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double LeftInverterAbsolutePhaseCurrentMin {
            get {
                return ((double)(this["LeftInverterAbsolutePhaseCurrentMin"]));
            }
            set {
                this["LeftInverterAbsolutePhaseCurrentMin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public double LeftInverterLinkVoltageDCXLagSpacing {
            get {
                return ((double)(this["LeftInverterLinkVoltageDCXLagSpacing"]));
            }
            set {
                this["LeftInverterLinkVoltageDCXLagSpacing"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public double LeftInverterLinkVoltageDCXLagMax {
            get {
                return ((double)(this["LeftInverterLinkVoltageDCXLagMax"]));
            }
            set {
                this["LeftInverterLinkVoltageDCXLagMax"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public double LeftInverterLinkVoltageDCXNofDataPoint {
            get {
                return ((double)(this["LeftInverterLinkVoltageDCXNofDataPoint"]));
            }
            set {
                this["LeftInverterLinkVoltageDCXNofDataPoint"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int LeftInverterLinkVoltageDCXLag {
            get {
                return ((int)(this["LeftInverterLinkVoltageDCXLag"]));
            }
            set {
                this["LeftInverterLinkVoltageDCXLag"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public double LeftInverterLinkVoltageDCMax {
            get {
                return ((double)(this["LeftInverterLinkVoltageDCMax"]));
            }
            set {
                this["LeftInverterLinkVoltageDCMax"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double LeftInverterLinkVoltageDCMin {
            get {
                return ((double)(this["LeftInverterLinkVoltageDCMin"]));
            }
            set {
                this["LeftInverterLinkVoltageDCMin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public double RightPCBTempXLagSpacing {
            get {
                return ((double)(this["RightPCBTempXLagSpacing"]));
            }
            set {
                this["RightPCBTempXLagSpacing"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public double RightPCBTempXLagMax {
            get {
                return ((double)(this["RightPCBTempXLagMax"]));
            }
            set {
                this["RightPCBTempXLagMax"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public double RightPCBTempXNofDataPoint {
            get {
                return ((double)(this["RightPCBTempXNofDataPoint"]));
            }
            set {
                this["RightPCBTempXNofDataPoint"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int RightPCBTempXLag {
            get {
                return ((int)(this["RightPCBTempXLag"]));
            }
            set {
                this["RightPCBTempXLag"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public double RightPCBTempMax {
            get {
                return ((double)(this["RightPCBTempMax"]));
            }
            set {
                this["RightPCBTempMax"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double RightPCBTempMin {
            get {
                return ((double)(this["RightPCBTempMin"]));
            }
            set {
                this["RightPCBTempMin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public double LeftPCBTempXLagSpacing {
            get {
                return ((double)(this["LeftPCBTempXLagSpacing"]));
            }
            set {
                this["LeftPCBTempXLagSpacing"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public double LeftPCBTempXLagMax {
            get {
                return ((double)(this["LeftPCBTempXLagMax"]));
            }
            set {
                this["LeftPCBTempXLagMax"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public double LeftPCBTempXNofDataPoint {
            get {
                return ((double)(this["LeftPCBTempXNofDataPoint"]));
            }
            set {
                this["LeftPCBTempXNofDataPoint"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int LeftPCBTempXLag {
            get {
                return ((int)(this["LeftPCBTempXLag"]));
            }
            set {
                this["LeftPCBTempXLag"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public double LeftPCBTempMax {
            get {
                return ((double)(this["LeftPCBTempMax"]));
            }
            set {
                this["LeftPCBTempMax"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double LeftPCBTempMin {
            get {
                return ((double)(this["LeftPCBTempMin"]));
            }
            set {
                this["LeftPCBTempMin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public double TotalAverageBatteryTempXLagSpacing {
            get {
                return ((double)(this["TotalAverageBatteryTempXLagSpacing"]));
            }
            set {
                this["TotalAverageBatteryTempXLagSpacing"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public double TotalAverageBatteryTempXLagMax {
            get {
                return ((double)(this["TotalAverageBatteryTempXLagMax"]));
            }
            set {
                this["TotalAverageBatteryTempXLagMax"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public double TotalAverageBatteryTempXNofDataPoint {
            get {
                return ((double)(this["TotalAverageBatteryTempXNofDataPoint"]));
            }
            set {
                this["TotalAverageBatteryTempXNofDataPoint"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int TotalAverageBatteryTempXLag {
            get {
                return ((int)(this["TotalAverageBatteryTempXLag"]));
            }
            set {
                this["TotalAverageBatteryTempXLag"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public double TotalAverageBatteryTempMax {
            get {
                return ((double)(this["TotalAverageBatteryTempMax"]));
            }
            set {
                this["TotalAverageBatteryTempMax"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double TotalAverageBatteryTempMin {
            get {
                return ((double)(this["TotalAverageBatteryTempMin"]));
            }
            set {
                this["TotalAverageBatteryTempMin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public double GearBoxTempXLagSpacing {
            get {
                return ((double)(this["GearBoxTempXLagSpacing"]));
            }
            set {
                this["GearBoxTempXLagSpacing"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public double GearBoxTempXLagMax {
            get {
                return ((double)(this["GearBoxTempXLagMax"]));
            }
            set {
                this["GearBoxTempXLagMax"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public double GearBoxTempXNofDataPoint {
            get {
                return ((double)(this["GearBoxTempXNofDataPoint"]));
            }
            set {
                this["GearBoxTempXNofDataPoint"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int GearBoxTempXLag {
            get {
                return ((int)(this["GearBoxTempXLag"]));
            }
            set {
                this["GearBoxTempXLag"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public double GearBoxTempMax {
            get {
                return ((double)(this["GearBoxTempMax"]));
            }
            set {
                this["GearBoxTempMax"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double GearBoxTempMin {
            get {
                return ((double)(this["GearBoxTempMin"]));
            }
            set {
                this["GearBoxTempMin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public double LenghtOfAlertList {
            get {
                return ((double)(this["LenghtOfAlertList"]));
            }
            set {
                this["LenghtOfAlertList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double GaugeLeftInverterSpeedMin {
            get {
                return ((double)(this["GaugeLeftInverterSpeedMin"]));
            }
            set {
                this["GaugeLeftInverterSpeedMin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public double GaugeLeftInverterSpeedMax {
            get {
                return ((double)(this["GaugeLeftInverterSpeedMax"]));
            }
            set {
                this["GaugeLeftInverterSpeedMax"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double GaugeRightInverterSpeedMin {
            get {
                return ((double)(this["GaugeRightInverterSpeedMin"]));
            }
            set {
                this["GaugeRightInverterSpeedMin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public double GaugeRightInverterSpeedMax {
            get {
                return ((double)(this["GaugeRightInverterSpeedMax"]));
            }
            set {
                this["GaugeRightInverterSpeedMax"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double GaugeLeftMechanicalPowerMin {
            get {
                return ((double)(this["GaugeLeftMechanicalPowerMin"]));
            }
            set {
                this["GaugeLeftMechanicalPowerMin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public double GaugeLeftMechanicalPowerMax {
            get {
                return ((double)(this["GaugeLeftMechanicalPowerMax"]));
            }
            set {
                this["GaugeLeftMechanicalPowerMax"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double GaugeRightMechanicalPowerMin {
            get {
                return ((double)(this["GaugeRightMechanicalPowerMin"]));
            }
            set {
                this["GaugeRightMechanicalPowerMin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public double GaugeRightMechanicalPowerMax {
            get {
                return ((double)(this["GaugeRightMechanicalPowerMax"]));
            }
            set {
                this["GaugeRightMechanicalPowerMax"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double GaugeVelocityXMin {
            get {
                return ((double)(this["GaugeVelocityXMin"]));
            }
            set {
                this["GaugeVelocityXMin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public double GaugeVelocityXMax {
            get {
                return ((double)(this["GaugeVelocityXMax"]));
            }
            set {
                this["GaugeVelocityXMax"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double GaugeVelocityYMin {
            get {
                return ((double)(this["GaugeVelocityYMin"]));
            }
            set {
                this["GaugeVelocityYMin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public double GaugeVelocityYMax {
            get {
                return ((double)(this["GaugeVelocityYMax"]));
            }
            set {
                this["GaugeVelocityYMax"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double WriteToDataLog {
            get {
                return ((double)(this["WriteToDataLog"]));
            }
            set {
                this["WriteToDataLog"] = value;
            }
        }
    }
}
